spring.application.name=hub
spring.datasource.url=jdbc:postgresql://localhost:5432/foro_db
spring.datasource.username=postgres
spring.datasource.password=nosemano23#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Variables JWT
api.security.secret=${JWT_SECRET:123456}